# Health check

GET http://127.0.0.1:8000/health
Accept: application/json

###

# Dashboard UI

GET http://127.0.0.1:8000/
Accept: text/html

###

# Router status

GET http://127.0.0.1:8000/status
Accept: application/json

###

# Public IP

GET http://127.0.0.1:8000/public-ip
Accept: application/json

###

# Switch to 3G

GET http://127.0.0.1:8000/mode/3g
Accept: application/json

###

# Switch to 4G

GET http://127.0.0.1:8000/mode/4g
Accept: application/json

###

# Reboot the router

GET http://127.0.0.1:8000/reboot
Accept: application/json

###

# Mobile data on

GET http://127.0.0.1:8000/mobile-data/on
Accept: application/json

###

# Mobile data off

GET http://127.0.0.1:8000/mobile-data/off
Accept: application/json

###

# Reconnect the router

GET http://127.0.0.1:8000/reconnect
Accept: application/json

###

# Rotate the connection
# /rotate returns immediately with {"status":"rotating"}; check /status for the final result.

GET http://127.0.0.1:8000/rotate
Accept: application/json
